testing & final adjustments
Ntare22/financial-modelling-app pull request #3
Opened 2022-01-06 21:15 UTC by Ntare22

add search feature for easy access
add testing and test various features

2022-01-06 22:25 UTC, bimbolabuari requested changes
Hi @Ntare22, 

You have done a good job so far 🚀  

## Highlights 🎉 

- The project uses Redux for state management and data retrieved from the API are stored in the Redux store correctly.
- It connects to the Redux store, using the redux hooks.

There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] Check the comments under the review

- Kindly record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:
  - a description of the project.
  - a demo of the project features.
  - you should also highlight some interesting piece of code or something you built that you are very proud of.
 
*For recording the video you can use tools like Loom that let you share a private link to the recording, and configure a shot that shows your computer screen and your face at the same time in a small picture.*

-  [ ] Create unit tests for pure functions in your Redux code.
- [ ] Create integration tests for your application using the React Testing Library.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

2022-01-06 22:25 UTC, bimbolabuari commented on README.md
> +- etc
The "Acknowledgements" section should give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the[ author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the Creative Commons License.

Kindly add this 🙂

2022-01-06 22:25 UTC, bimbolabuari commented on README.md
> +
Kindly deploy the application using Heroku, Netlify, or GitHub Pages, and a link to the deployed project should be present in the README. ✊

2022-01-06 22:25 UTC, bimbolabuari commented on src/components/Stocks.js
> +  // eslint-disable-next-line max-len
Let's remove all disabled Linters, Linting helps with more cleaner and professional code 👍 

Kindly check for other occurrences 🙂

2022-01-06 22:25 UTC, bimbolabuari commented on src/styles/index.scss
> +@import url('./search.scss')
As required, lets stick to the design template given 👍 

> Your design

![image](https://user-images.githubusercontent.com/66112760/148460268-b46674cd-a24a-4814-b13d-5c1eab58c432.png)

> Original design template 
![image](https://user-images.githubusercontent.com/66112760/148460470-6215dde1-f806-43e3-9811-fc5aa624117f.png)

Kindly follow these design guidelines, including:
 - Colors (select one main color for your website).
 - Typography: font face, size and weight.
 - Layout: composition and space between elements.

2022-01-07 13:06 UTC, AshakaE approved these changes
### Hi @Ntare22  🙋‍♀️, 

# STATUS APPROVED ✔
   
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 16:45 UTC, merged